export const HOME = "/"
export const ROLES = "/roles"
export const COURSES = "/courses"
export const SKILLMAINTENANCE = "/SkillMaintenance"
export const CREATESKILL = "/CreateSkill"
export const EDITSKILL = "/EditSkill"

export const LEARNINGJOURNEY = "/learningjourney"
export const SKILLASSIGNMENT = "/SkillAssignment"
export const SELECTSKILLS = "/SelectSkills"
export const ROLEMAINTENANCE = "/RoleMaintenance"
export const CREATEROLE = "/CreateRole"
export const UPDATEROLE = "/UpdateRole"
